group: travis_latest
language: python
cache: pip
python:
  - 3.7
matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
install:
  - sudo apt-get update
  - hash -r
  - pip3 install -r requirements.txt
  - pip3 install flake8
  - pip3 install codecov
  - python setup.py install
before_script:
  - flake8 --config=.flake8 .
  - flake8 . --count --exit-zero --statistics --select=E,F,W,C90
script:
  - python -m unittest
  - cd tests
  - coverage run test_parser.py 
  - coverage report -m
after_sucess:
  - codecov
#notifications:
  #on_success: change
  # `always` will be the setting below once code changes slow down
  #on_failure: change